" General
set nu!                        " show line numbers
set nocompatible               " prevent emulation of vi settings, hence it's bugs and limitations
set nobackup                   " don't create any backup files (~)
set noswapfile                 " don't create any swap files (.swp)
set nowrap                     " don't wrap file content
set hls                        " highlight search results
set incsearch                  " show search results as you are typing
set backspace=indent,eol,start " enable proper usage of the del key
set virtualedit=block          " allow virtual editing in block mode (where there is no actual character)

" Tabs and indentation
set tabstop=2                  " 2 columns per tab
set expandtab                  " insert spaces when tabbing
set shiftwidth=2               " 2 column indentation when reindenting
set softtabstop=2              " 2 stops for every tab

" File types and encoding
set encoding=utf-8             " create files using utf-8 encoding
set fileencodings=ucs-bom,utf-8,iso-8859-1 " enable support for files with and without bom characters
set fileformat=unix            " force unix file format for new files

" Display
syntax on
filetype on
filetype indent on
filetype plugin on
set ofu=syntaxcomplete#Complete
set completeopt=longest,menuone
set statusline=                                          " clear statusline
set statusline+=%<                                       " cut at start
set statusline+=%f%m%r                                   " filename + flags
set statusline+=\ %y[%{strlen(&fenc)?&fenc:&enc}/%{&ff}] " type & encoding
set statusline+=\ #%n                                    " buf #
set statusline+=%=                                       " right align the rest
set statusline+=[%03.b/%02.B]                            " char code at cursor
set statusline+=[%v,%l/%L(%p%%)]                         " cursor position
set laststatus=2

" Key maps
inoremap <C-Space> <C-x><C-o>
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
inoremap <expr> <C-n> pumvisible() ? '<C-n>' : '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
inoremap <expr> <M-,> pumvisible() ? '<C-n>' : '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'

" Ctrl+c / Ctrl+v for copy/paste
vmap <C-C> "+yi
vmap <C-X> "+xi
imap <C-V> <esc>"+gPi

" Operating system specific
if has("unix")

elseif has("win32")

endif

" gvim specific
if has("gui_running") 
  colorscheme wombat
  set background=dark
	set guioptions-=T            " remove the toolbar
	set guioptions-=m            " remove the menubar
	
	if has("gui_gtk2")
    set guifont=Monaco\ 9
	elseif has("gui_win32")
    set guifont=Consolas:h9:cANSI
	endif
endif

